---

- name: Setup Playbook for WKSHP-DataVisu101 appliance
  hosts: '{{ RTARGET }}'
  tasks:
    - name: Setup docker based appliance
      include_tasks: "{{ ANSIBLEDIR }}/setup_docker_based_appliance.yml"

